# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d26cb4fefbcfafa2331afc0ef189cf2eb73ffa0eee6bda2bafbb788ffe09e18f817fb327a90dde71690f16b236fc32b694e13c28854e944e56d20042ea4486c7

test:
  secret_key_base: e8000f78c4777ad91c56858fc99bee24a27925bc53259af6887c5cb385da6b52db1c2b0bde68c262a717e6d19a61d39c69f4c638e751dbb37995f89979c30f6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
